name: Scan with Sonar Scanner
author: Mathrix Education SA
description: Sonar Scanner on Github Actions.
branding:
  color: gray-dark
  icon: upload-cloud
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  version:
    description: The Sonar Scanner version.
    required: true
  with-jre:
    description: Use the bundled JRE.
    required: false
    default: 'false'
  options:
    description: Default Sonar Scanner options. Read as a YAML document (you may use the pipe '|' YAML operator).
    required: false
  typescript:
    description: >
      Install TypeScript during setup (simply run `npm i typescript`). Required if your project uses Typescript and if
      the node module `typescript` is  not already installed.
    required: false
    default: 'false'
  unshallow:
    description: Fetch a full clone of the repository. Useful when using the SCM feature of Sonar Scanner.
    required: false
    default: 'false'
  scan:
    description: Run Sonar Scanner immediately in the current working directory.
    required: false
    default: 'false'
  args:
    description: Additional flag to append during the scan. Ignored if `scan` is false.
    required: false
